### ISSUE TITLE
Color/other non-markdown text styles

### ISSUE THREAD

**Issue by sqrrrl** [googlesamples/md2googleslides#1]
Feature request to add additional styling support, particularly colors, using {attr} syntax

# Title{foreground-color=red}

**Comment by githarkirat** [comment]
since colour and undeline are not supported natively in markdown, why not just add a `# <span style='color:#FF0000'> Title</span> ` inline element

**Comment by sqrrrl** [comment]
Yes, probably will end up doing that, though right now inline span elements are ignored. It's implemented for syntax highlighted code, just needs to be generalized for use in other elements.

**Comment by sqrrrl** [comment]
Fixed in next version.
