### ISSUE TITLE
Question: how do i get the nice theme you have in your readme example?

### ISSUE THREAD

**Issue by tomer-ben-david** [googlesamples/md2googleslides#12]

**Comment by ralphbean** [comment]
Same question here.  Not sure how to style the slides.

**Comment by ralphbean** [comment]
Ah, see #5.

**Comment by tomer-ben-david** [comment]
@ralphbean  did it change the whole theme to be seen as the readme example? I tried changing the theme afterwards in google-slides but its still not like the beautiful one in the readme, is it for you the same?

**Comment by rjhilgefort** [comment]
@tomer-ben-david I was able to change my theme after generation and it applied to all slides with no issues.

**Comment by tomer-ben-david** [comment]
thanks
