### ISSUE TITLE
How did you style the examples with blue background?

### ISSUE THREAD

**Issue by mobty** [googlesamples/md2googleslides#5]
I would like to format the background color of my slides but I can't find a method to match your example in the readme.

**Comment by sqrrrl** [comment]
You have to do it via the Slides API after you generate the presentation. "Slide->Change Theme" from the menu will display all the available themes. Picking one will update all the slides. Most text will automatically update to reflect the new theme, though anything with manual styles applied (e.g. syntax-highlighted code) won't.

Unfortunately the ability to change the theme isn't available via the API yet. If it gets added I'll update the tool to allow setting it either via markup or command line switch.

**Comment by rossmeissl** [comment]
@sqrrrl Just curious if you think the ability to set theme by API will ever arrive?
